Repository SansamForce/team-building-frontend, pull requests merged in 2024-10, with the labels that each got.

#2 [TEST] 풀리퀘 템플릿 테스트
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/components/HelloWorld.vue
  frontend/src/components/TestComponent.vue
  frontend/src/components/TheWelcome.vue
  frontend/src/components/WelcomeItem.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/main.js
Labels: CHORE, REFACTOR, TEST

#4 [FEAT] Tailwind CSS 추가 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/styles/tailwind.css
  frontend/tailwind.config.js
Labels: FEAT

#6 [FEAT] BootStrap 연결 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
Labels: FEAT

#17 [FEAT] 로그인 페이지 퍼블리싱 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/루피.jpg
  frontend/src/App.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/user/LoginComponent.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/tailwind.config.js
Labels: FEAT, REFACTOR

#19 [FEAT] 내 프로젝트, 팀 상세보기
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/beyond-hanhwa.png
  frontend/src/App.vue
  frontend/src/components/project/ProjectDetail.vue
  frontend/src/components/project/ProjectItem.vue
  frontend/src/components/project/ProjectList.vue
  frontend/src/components/team/TeamChatComponent.vue
  frontend/src/components/team/TeamDetail.vue
  frontend/src/components/team/TeamMember.vue
  frontend/src/components/team/TeamSchedule.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/main/Main.vue
  frontend/src/views/project/ProjectDetail.vue
  frontend/src/views/project/ProjectList.vue
  frontend/src/views/team/TeamDetail.vue
Labels: FEAT

#28 [FEAT] 로그인 api 연동 완료
  frontend/src/App.vue
  frontend/src/components/TestComponent.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/user/LoginComponent.vue
  frontend/src/router/index.js
  frontend/src/stores/UserStore.js
Labels: BUG, FEAT, REFACTOR

#31 [FEAT] 회원가입 페이지 퍼블리싱 완료 및 api 연동
  frontend/src/router/index.js
  frontend/src/views/user/LoginView.vue
  frontend/src/views/user/SignupView.vue
Labels: FEAT, REFACTOR

#36 [BUG] 로그인 후 새로고침하면 로그인 풀리는 이슈 해결
  frontend/src/App.vue
  frontend/src/components/common/Header.vue
  frontend/src/stores/UserStore.js
Labels: BUG, FEAT, CHORE

#38 [FEAT] 관리자 프로젝트 생성 페이지 추가
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
  frontend/src/views/projectBoard/projectBoardList.vue
Labels: FEAT, CHORE

#39 [FEAT] 메인 화면 퍼블리싱
  frontend/package-lock.json
  frontend/src/components/common/Header.vue
  frontend/src/views/main/Main.vue
Labels: FEAT, CHORE, REFACTOR

#40 [FEAT] 회원 프로젝트 모집글 신청 기능 페이지 구현
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
Labels: FEAT, CHORE

#43 [REFACTOR] 전역 라우트 가드 설정 작업
  frontend/src/router/index.js
Labels: REFACTOR

#46 [REFACTOR] 페이지 구조 변경, 아이콘 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/team/TeamChatComponent.vue
  frontend/src/components/team/TeamDetail.vue
  frontend/src/components/team/TeamMember.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/main/MainView.vue
  frontend/src/views/project/ProjectDetailView.vue
  frontend/src/views/project/ProjectListView.vue
  frontend/src/views/team/TeamChatView.vue
  frontend/src/views/team/TeamDetail.vue
  frontend/src/views/team/TeamDetailView.vue
Labels: REFACTOR

#50 [FIX] Main.vue 파일 통합 작업
  frontend/src/views/main/Main.vue
  frontend/src/views/main/MainView.vue
Labels: BUG

#55 [FEAT] 프로젝트 신청 회원 API 연동 완료
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
Labels: FEAT, REFACTOR

#59 [REFACTOR] 회원가입 시 한글 성별 입력
  frontend/src/views/user/SignupView.vue
Labels: REFACTOR

#63 [FEAT] 비회원 프로젝트 게시물 조회 기능 추가
  frontend/src/router/index.js
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
Labels: FEAT

#64 [REFACTOR] 프로젝트 게시글 마감시 신청 블락하기
  frontend/src/views/projectBoard/AdminBoardDetail.vue
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
  frontend/src/views/projectBoard/projectBoardList.vue
Labels: BUG, REFACTOR

#69 [FEAT] 프로젝트 생성 회원 추가 구현
  frontend/src/views/projectBoard/AdminBoardDetail.vue
  frontend/src/views/projectBoard/projectBoardList.vue
Labels: FEAT, CHORE

#73 [REFACTOR] 프로젝트 신청 회원 개발분야 조회 추가
  frontend/src/views/projectBoard/AdminBoardDetail.vue
Labels: REFACTOR

#75 [FEAT] 헤더 토글 바 추가 작업 (회원, 강사)
  frontend/src/components/common/Header.vue
Labels: FEAT

#76 [FEAT] 강사 프로젝트 생성
  frontend/public/images/team-image.png
  frontend/src/components/project/MemberProjectDetail.vue
  frontend/src/components/project/MentorProjectDetail.vue
  frontend/src/components/project/MentorProjectTeamList.vue
  frontend/src/views/project/ProjectDetailView.vue
  frontend/src/views/project/ProjectTeamListView.vue
  frontend/src/views/team/TeamDetailView.vue
Labels: FEAT

#83 [FEAT] 회원의 프로젝트 신청 리스트 조회 페이지 구현 완료
  frontend/src/router/index.js
  frontend/src/views/projectBoard/AppliedProjectList.vue
  frontend/src/views/projectBoard/ProjectBoardDetail.vue
Labels: FEAT, REFACTOR

#85 [FEAT] 모든 페이지에 마우스 드래그 안되게 하는 작업
  frontend/src/App.vue
Labels: FEAT

#94 [REFACTOR] 팀 조회 시 프로젝트 SEQ를 이용하여 조회
  frontend/src/views/project/ProjectDetailView.vue
Labels: REFACTOR

#96 [REFACTOR] 헤더 회원가입 로그인 위치 변경
  frontend/src/components/common/Header.vue
Labels: BUG, REFACTOR

#100 [REFACTOR] 강사 프로젝트 조회 시 화면이 안보이는 오류 수정
  frontend/src/views/project/ProjectDetailView.vue
  frontend/src/views/project/ProjectTeamListView.vue
  frontend/src/views/team/TeamDetailView.vue
Labels: BUG, FEAT, REFACTOR

#104 [REFACTOR] 팀 빌딩 완료시 팀 채팅방 추가 구현
  frontend/src/views/team/TeamBuildingView.vue
Labels: REFACTOR

#114 [FEAT] 강사 평가 페이지 퍼블리싱 및 API 연동 작업
  frontend/index.html
  frontend/src/components/project/ProjectMember.vue
  frontend/src/components/project/Teambuilding.vue
  frontend/src/stores/UserStore.js
  frontend/src/views/project/ProjectMemberListView.vue
  frontend/src/views/team/TeamBuildingView.vue
Labels: BUG, FEAT, REFACTOR

#117 [REFACTOR] 마이페이지 이미지 수정 안되는 오류 해결
  frontend/src/stores/MyPageStore.js
  frontend/src/views/mypage/Mypage.vue
Labels: FEAT, REFACTOR

#119 [CHORE] 불필요한 로그 삭제
  frontend/src/stores/UserStore.js
Labels: CHORE

#133 [docs] 회원팀채팅,평가 추가
  frontend/src/images/member/PROJECT/14_회원_팀채팅.gif
  frontend/src/images/member/PROJECT/17_회원_팀원평가.gif
Labels: DOCS
